server:
  port: 8080

security:
  jwt:
    token:
      secret-key: my-secret

#need to check what good practice and stuff for this is
spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/backenddb
    username: sathvik
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
     hibernate:
       dialect: org.hibernate.dialect.PostgreSQLDialect
       format_sql: true
    show-sql: true
  main:
    web-application-type: servlet
  sql:
    init:
      platform: postgres